## Service for Admin
apiVersion: v1
kind: Service
metadata:
  name: act-admin-clusterip
spec:
  ports:
    - name: act-admin
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: act-admin
  type: ClusterIP

---

## Admin Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: act-admin
  labels:
    app: act-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: act-admin
  template:
    metadata:
      labels:
        app: act-admin
    spec:
      containers:
        - resources: {}
          name: act-admin
          image: hicsail/act-admin:main
          terminationMessagePath: /dev/termination-log
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
      imagePullSecrets:
        - name: dockerhub-image-pull-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
